name: CustomMobs
version: 1.0
author: Hulaa
main: de.hulaa.CustomMobs.CustomMobsMain
description: Customized mobs and let them spawn
commands:
     cspawn:
          description: Spawn of CustomMobs for Testing
          usage: </command> [value]