name: HMCServerAdmin
version: 1.1
author: Hulaa
main: me.hulaa.info.HMCAdmin
commands:
     info:
          description: Show server info!
          usage: </command>
     speed:
          description: Set player walk and flyspeed (0.0 to 1.0)
          usage: </command> [value]
     heal:
          description: Heal the player to full health and hunger
          usage: </command>
     clearinv:
          description: Clear the inventory
          usage: </command>
     town:
          description: Teleport to town
          usage: </command> [value]
     towninfo:
          description: List available towns to teleport
          usage: </command>
     health:
          description: Set player health (0 to 1.000.000)
          usage: </command> [value]
     ad:
          description: Set player attack damage (0 to 1.000.000)
          usage: </command> [value]
     c:
          description: Set gamemode to creative
          usage: </command>
     s:
          description: Set gamemode to survival
          usage: </command>